# 部署前请修改baseurl
baseurl      = "https://neko-suwako.github.io/homepage/"
languageCode = "zh-cn"
title        = "猫窝"

# 主题国际化支持
# 查看所有可用值：https://github.com/CaiJimmy/hugo-theme-stack/tree/master/i18n
defaultContentLanguage = "zh-cn"

# 如果DefaultContentLanguage是[zh-cn ja ko]之一，请设置hasCJKLanguage为true
# 这将使.Summary和.WordCount对CJK语言正确显示
hasCJKLanguage = true

# 使用前请修改为你的Disqus shortname
disqusShortname = "neko-suwako"

[pagination]
    pagerSize = 5
