# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
    identifier = "bilibili"
    name       = "哔哩哔哩"
    url        = "https://space.bilibili.com/8412735"

    [social.params]
        icon = "bilibili"

