# Configure main menu and social menu
[[main]]
identifier = "home"
name = "首页"
url = "/"
[main.params]
icon = "home"

[[main]]
identifier = "archives"
name = "归档"
url = "/page/archives/"
[main.params]
icon = "archive"

[[main]]
identifier = "links"
name = "链接"
url = "/page/links/"
[main.params]
icon = "link"

[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/CaiJimmy/hugo-theme-stack"

    [social.params]
        icon = "brand-github"

[[social]]
    identifier = "twitter"
    name       = "Twitter"
    url        = "https://twitter.com"

    [social.params]
        icon = "brand-twitter"
