# æ”¾åœ¨è¿™äº›éƒ¨åˆ†ä¸‹çš„é¡µé¢å°†åœ¨é¦–é¡µå’Œå½’æ¡£é¡µé¢æ˜¾ç¤º
mainSections = ["post"]
# åœ¨RSSä¸­è¾“å‡ºé¡µé¢çš„å®Œæ•´å†…å®¹
rssFullContent = true
favicon        = "img/favicon.png"

# å¯æ¥å—çš„å€¼: "default", "lastmod"
# default = å‚è§ https://gohugo.io/quick-reference/glossary/#default-sort-order
# lastmod = æŒ‰æœ€åä¿®æ”¹æ—¥æœŸæ’åºï¼Œé™åº
SortBy              = "default"

[footer]
    since      = 2020
    customText = ""

[dateFormat]
    published   = ":date_full"
    lastUpdated = ":date_full"

[sidebar]
#    emoji    = "ğŸ¥"
    subtitle = "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
    avatar   = "img/avatar.png"

[article]
    headingAnchor = false
    math          = false
    readingTime   = true

    [article.license]
        enabled = true
        default = "Licensed under CC BY-NC-SA 4.0"

[widgets]
    homepage = [
        { type = "search" },
        { type = "archives", params = { limit = 5 } },
        { type = "categories", params = { limit = 10 } },
        { type = "tag-cloud", params = { limit = 10 } },
    ]
    page = [{ type = "toc" }]

[opengraph.twitter]
    site = ""
    card = "summary_large_image"

[colorScheme]
    toggle  = true
    default = "auto"

## è¯„è®º
[comments]
    enabled  = true
    provider = "disqus"

    # æŸ¥çœ‹æ‰€æœ‰å¯ç”¨é…ç½®: https://github.com/CaiJimmy/hugo-theme-stack/blob/master/config/_default/params.toml
    # ä»é‚£é‡Œå¤åˆ¶ä½ éœ€è¦çš„é…ç½®å¹¶ç²˜è´´åˆ°è¿™é‡Œã€‚
